---
title: "Comparison with mgcv"
author: "James T. Thorson"
output: rmarkdown::html_vignette
#output: rmarkdown::pdf_document
vignette: >
  %\VignetteIndexEntry{Comparison with mgcv}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteDepends{pdp}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
# Install locally
#  devtools::install_local( R'(C:\Users\James.Thorson\Desktop\Git\tinyVAST)', force=TRUE )
# Build
#  setwd(R'(C:\Users\James.Thorson\Desktop\Git\tinyVAST)'); devtools::build_rmd("vignettes/VAST.Rmd")
# PDF
#  library(rmarkdown); render( "vignettes/VAST.Rmd", pdf_document())
```

```{r setup, echo=TRUE, message=FALSE}
library(tinyVAST)
library(fmesher)
set.seed(101)
```

`tinyVAST` is an R package for fitting vector autoregressive spatio-temporal (VAST) models.
We here explore the capacity to specify the vector-autoregressive spatio-temporal component

```{r, eval=TRUE, echo=TRUE, message=FALSE, fig.width=6, fig.height=6}
# Simulate settings
theta_xy = 0.2
n_x = n_y = 20
n_t = 10

# Simulate GMRFs
R = exp(-theta_xy * abs(outer(1:n_x, 1:n_y, FUN="-")) )
d1 = mvtnorm::rmvnorm(n_t, sigma=0.2*kronecker(R,R) )
d2 = mvtnorm::rmvnorm(n_t, sigma=0.2*kronecker(R,R) )
d = abind::abind( d1, d2, along=3 )

# Project through time and add mean
B = matrix( c(0,0,0,0), ncol=2 )
for( t in seq_len(n_t) ){
  if(t>1) d[t,,] = d[t-1,,]%*%B + d[t,,]
}
d[,,1] = d[,,1] + 2
d[,,2] = d[,,2] + 3

# Shape into longform data-frame and add error
Data = data.frame( expand.grid(time=1:n_t, x=1:n_x, y=1:n_y, "var"=c("d1","d2")), z=as.vector(d))
Data$n = Data$z + rnorm(nrow(Data), sd=0.2)

# make mesh
mesh = fm_mesh_2d( Data[,c('x','y')] )

# Define sem
sem = "
  #d1 -> d1, -1, b11
  #d2 -> d2, -1, b22
  #d1 -> d2, -1, b12
  #d2 -> d1, -1, b12
"

# fit model
out = fit( sem = sem,
           data = Data,
           formula = n ~ var,
           spatial_graph = mesh,
           quiet = TRUE )
out
```

