name: sanitizers

on:
  workflow_dispatch:
  push:
    branches: [main, dev]

jobs:
  san-check:
    runs-on: ubuntu-latest

    container:
      #image: ghcr.io/r-hub/containers/gcc13:latest       # Doesn't find error
      image: ghcr.io/r-hub/containers/clang-asan:latest   # Same as Ripley

    env:
      UBSAN_OPTIONS: print_stacktrace=1
      ASAN_OPTIONS: detect_leaks=0
      _R_CHECK_FORCE_SUGGESTS_: false

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          R -q -e 'install.packages("pak")'
          R -q -e 'pak::pkg_install(c("local::.", "rcmdcheck", "knitr", "rmarkdown", "AER", "MARSS", "testthat"))'
          # R -q -e 'pak::pkg_install(c("phylopath", "reshape", "dynlm", "ggpubr", "vars", "DHARMa"))'    # Oher SUGGESTS packages

      - name: Run check
        run: |
          # R -q -e 'rcmdcheck::rcmdcheck(args = c("--no-manual", "--no-vignettes", "--no-build-vignettes", "--no-examples", "--no-tests"), build_args = c("--no-build-vignettes", "--no-build-vignettes"), error_on = "error")'
          R -q -e 'rcmdcheck::rcmdcheck(args = c("--no-manual", "--no-vignettes", "--no-build-vignettes"), build_args = c("--no-build-vignettes", "--no-build-vignettes"), error_on = "error")'

